[package]
name = "botrs"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Core - a simple bot to conquer the world"
repository.workspace = true
license.workspace = true
publish.workspace = true
readme = "../README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
llm-chain = { git = "https://github.com/ssoudan/llm-chain", branch = "fix", default-features = false, features = ["serialization"] }
#llm-chain-openai = { git = "https://github.com/ssoudan/llm-chain", branch = "fix", default-features = false, features = ["serialization"] }
#llm-chain = { path = "../llm-chain/llm-chain", default-features = false, features = ["serialization"] }
#llm-chain-openai = { path = "../llm-chain/llm-chain-openai", default-features = false, features = [] }

tokio = { version = "1.27.0" }
serde = { version = "1.0.160", features = ["derive"] }
serde_yaml = "0.9.21"

regex = "1.7.3"

colored = "2.0.0"

tiktoken-rs = { version = "0.4.1", features = ["async-openai"] }
async-openai = "0.10.3"

thiserror = "1.0.40"

[dev-dependencies]
indoc = "2"
