[package]
name = "botrs"
version = "0.1.0"
edition = "2021"
authors = ["Sebastien Soudan <sebastien.soudan@gmail.com>"]
description = "A simple bot to conquer the world"
repository = "https://github.com/ssoudan/botrs"
license = "MIT/Apache-2.0"
publish = false
readme = "README.md"

keywords = ["bot", "language-model"]
categories = ["science"]

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
dotenvy = "0.15.7"
huelib = { git = "https://github.com/ssoudan/huelib-rs/", branch = "master" }
llm-chain = { git = "https://github.com/ssoudan/llm-chain", branch = "main" }
llm-chain-openai = { git = "https://github.com/ssoudan/llm-chain", branch = "main" }
#llm-chain = { path = "../llm-chain/llm-chain" }
#llm-chain-openai = { path = "../llm-chain/llm-chain-openai" }

tokio = { version = "1.27.0", features = ["full"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_yaml = "0.9.21"

regex = "1.7.3"

colored = "2.0.0"