[package]
name = "sapiens_cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "The cli interface of a simple bot to conquer the world"
repository.workspace = true
license.workspace = true
publish.workspace = true
readme = "../README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
sapiens = { path = "../sapiens", version = "0.2.0" }
sapiens_tools = { path = "../sapiens_tools", version = "0.2.0" }

tokio = { version = "1.27.0", features = ["full"] }

clap = { version = "4.2.3", features = ["derive"] }

dotenvy = "0.15.7"

huelib = { version = "0.13.2", git = "https://github.com/ssoudan/huelib-rs/", branch = "master" }

async-openai = "0.10.3"
