[package]
name = "sapiens"
version= "0.2.2"
edition.workspace = true
authors.workspace = true
description = "Core - Sapiens"
repository.workspace = true
license.workspace = true
publish.workspace = true
readme = "../README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
llm-chain = { version = "0.6.2", git = "https://github.com/ssoudan/llm-chain", branch = "main", default-features = false, features = [] }

tokio = { version = "1.27.0" }
tracing = "0.1.37"

serde = { version = "1.0.160", features = ["derive"] }
serde_yaml = "0.9.21"

regex = "1.8.1"

async-trait = "0.1.68"

tiktoken-rs = { version = "0.4.1", features = ["async-openai"] }
async-openai = "0.10.3"

thiserror = "1.0.40"

[dev-dependencies]
indoc = "2"
