[package]
name = "sapiens"
version= "0.4.1"
edition.workspace = true
authors.workspace = true
description = "Core - Sapiens"
repository.workspace = true
license.workspace = true
publish.workspace = true
readme = "../README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
tokio = { version = "1.28.0" }
tracing = "0.1.37"
async-trait = "0.1.68"

serde = { version = "1.0.160", features = ["derive"] }
serde_yaml = "0.9.21"

regex = "1.8.1"

tiktoken-rs = { version = "0.4.2", features = ["async-openai"] }
async-openai = "0.10.3"

thiserror = "1.0.40"

[dev-dependencies]
indoc = "2"
insta = { version = "1.29.0", features = ["yaml"] }
