[package]
name = "sapiens_exp"
version= "0.4.1"
edition.workspace = true
authors.workspace = true
description = "Experiments - Sapiens"
repository.workspace = true
license.workspace = true
publish.workspace = true
readme = "../README.md"
keywords.workspace = true
categories.workspace = true

[features]
default = [ ]

[dependencies]
sapiens = { path = "../sapiens", version = "^0.5.0" }
sapiens_tools = { path = "../sapiens_tools", version = "^0.5.0", default-features = false }

tracing = "0.1.38"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

tokio = { version = "1.28.0", features = ["full"] }
async-trait = "0.1.68"

serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"

pyo3 = { version = "0.18.3", features = [] }
pyo3-asyncio = { version = "0.18.0", features = ["attributes", "tokio-runtime"] }

clap = { version = "4.2.5", features = ["derive"] }
colored = "2.0.0"
dotenvy = "0.15.7"

huelib2 = { version = "0.13.3", optional = true }
