[alias]
xtask = "run --package xtask --bin xtask --"
lint = "run --package xtask --bin xtask lint --"
validate = "run --package xtask --bin xtask validate"
todo = "run --package xtask --bin xtask todo --"
pre_commit = "run --package xtask --bin xtask validate --strict"

[profile.ci]
failure-output = "immediate-final"
# Do not cancel the test run on the first failure.
fail-fast = false

[profile.ci.junit]
path = "junit.xml"

[build]
rustflags = []
