[package]
name = "sapiens_tools"
version= "0.4.0"
edition.workspace = true
authors.workspace = true
description = "The tools - Sapiens"
repository.workspace = true
license.workspace = true
publish.workspace = true
readme = "../README.md"
keywords.workspace = true
categories.workspace = true

[features]
default = ["wiki", "arxiv", "summarize"]
# Hue lights
hue = ["dep:huelib2"]
# MediaWiki: Wikipedia, Wikidata
wiki = ["dep:mediawiki", "dep:serde_json"]
# arXiv
arxiv = ["dep:arxiv-rs"]
# Summarization
summarize = ["dep:async-openai"]

[dependencies]
sapiens = { path = "../sapiens", version = "^0.4.0" }
sapiens_derive = { path = "../sapiens_derive", version = "^0.3.1" }

huelib2 = { version = "0.13.3", optional = true }
mediawiki = { version = "0.2.10", optional = true  }

arxiv-rs = { version = "0.1.5", optional = true }

serde = { version = "1.0.160", features = ["derive"] }
serde_yaml = "0.9.21"
serde_json = { version = "1.0.96", optional = true }

tokio = { version = "1.28.0", features = ["macros"] }
async-trait = "0.1.68"

regex = "1.8.1"
lazy_static = "1.4.0"

pyo3 = { version = "0.18.3", features = [] }

async-openai = { version = "0.10.3", optional = true }

convert_case = "0.6.0"

thiserror = "1.0.40"

[dev-dependencies]
indoc = "2"
serde_json = "1.0.96"
insta = { version = "1.29.0", features = ["yaml"] }
tokio = { version = "1.28.0", features = ["macros"] }
pyo3-asyncio = { version = "0.18.0", features = ["attributes", "tokio-runtime", "testing"]  }

[package.metadata.cargo-udeps.ignore]
normal = ["pyo3-asyncio"]

[[test]]
name = "e2e"
path = "tests/e2e.rs"
harness = false
