[package]
name = "sapiens_tools"
version= "0.2.1"
edition.workspace = true
authors.workspace = true
description = "The tools - a simple bot to conquer the world"
repository.workspace = true
license.workspace = true
publish.workspace = true
readme = "../README.md"
keywords.workspace = true
categories.workspace = true

[features]
default = ["hue"]
# Hue lights
hue = ["dep:huelib2"]

[dependencies]
sapiens = { path = "../sapiens", version = "^0.2.1" }
sapiens_derive = { path = "../sapiens_derive", version = "^0.2.1" }

huelib2 = { version = "0.13.3", optional = true }

serde = { version = "1.0.160", features = ["derive"] }
serde_yaml = "0.9.21"

regex = "1.7.3"

pyo3 = { version = "0.18.3", features = ["auto-initialize"] }

colored = "2.0.0"

tiktoken-rs = { version = "0.4.1", features = ["async-openai"] }
async-openai = "0.10.3"

convert_case = "0.6.0"

thiserror = "1.0.40"

[dev-dependencies]
indoc = "2"
