[package]
name = "botrs_tools"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "The tools - a simple bot to conquer the world"
repository.workspace = true
license.workspace = true
publish.workspace = true
readme = "../README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
botrs = { path = "../botrs" }

llm-chain = { git = "https://github.com/ssoudan/llm-chain", branch = "fix", default-features = false, features = ["serialization"] }

serde = { version = "1.0.160", features = ["derive"] }
serde_yaml = "0.9.21"

regex = "1.7.3"

pyo3 = { version = "0.18.3", features = ["auto-initialize"] }

colored = "2.0.0"

tiktoken-rs = { version = "0.4.1", features = ["async-openai"] }
async-openai = "0.10.3"

convert_case = "0.6.0"

thiserror = "1.0.40"
