name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install lld
      run: sudo apt-get update && sudo apt-get install -y lld wget unzip
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
    - name: Install protoc and protoc-gen-rust
      uses: arduino/setup-protoc@v1
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: cargo build --workspace
    - name: 'Create env file'
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
    - name: Test (dependabot)
      if: github.actor == 'dependabot[bot]'
      run: cargo test --workspace --features disable-test-dependabot
    - name: Test
      if: github.actor != 'dependabot[bot]'
      run: cargo test --workspace

  check:
    runs-on: ubuntu-latest

    steps:
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
        components: clippy
    - name: Install protoc and protoc-gen-rust
      uses: arduino/setup-protoc@v1
    - name: Install cargo-all-features
      run: cargo install cargo-all-features
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check (all-features)
      run: cargo check-all-features --workspace
    - name: Clippy
      run: cargo clippy --all-targets --all-features --workspace -- -D warnings

